# Generated by Django 4.1.7 on 2023-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLthietbi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình ảnh'),
        ),
    ]
