# Generated by Django 4.2.1 on 2023-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLthietbi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ'),
        ),
    ]
